### PR TITLE
adds initial plugin security policy for covering permissions under ES 2

### PR DESCRIPTION
**Pull request by dermidgen**
References #18

### CODE REVIEW

**Comment by jimmidyson** [comment]
Does this work for you?

Wonder if we should be more restrictive & fix only the security issue with `permission java.net.NetPermission "getProxySelector";`?

**Comment by dermidgen** [comment]
I have no real way of testing here; sorry - I'm flying blind.  

There's _not_ just an issue with `permission java.net.NetPermission "getProxySelector"`; it's also the filesystem permissions to read `/var/run/secrets/kubernetes.io/*` for `ca.crt` and `token`.

**Comment by jimmidyson** [comment]
That's an odd one. Would you be able to check the file permissions on the
mounted secrets? Works here for me but I'm on a customised disto of
kubernetes.

**Comment by dermidgen** [comment]
Yeah - it's owned by root and readable by users; just not by Java. This started when running ES as a user other than root.

**Comment by jimmidyson** [comment]
That's interesting. I was expecting permissions to be `644`. You're seeing them set as `640`?

**Comment by ant31** [comment]
Hi,
I have the same issue here. 
`/var/run/secrets/kubernetes.io/*`
Files are 444

I think it is a mounted readOnly dir.

**Comment by jimmidyson** [comment]
444 should be fine. Can you also share the permissions on the dir?

**Comment by dermidgen** [comment]
Sorry, yeah 444 and it's Kubernetes 1.1.1 on Google Container Engine

**Comment by danielschonfeld** [comment]
Sorry for flooding,on both the issue and here, but we are running into the same thing.  Permissions as far as the fielsytem are correct but it seems like an exception generated by Java's Security Manager.

I've posted an example on the original issue.

**Comment by jimmidyson** [comment]
Going to close this now that we've figure out we can't do this simply by adding security policy to plugin. Seems like we'll need to wait for a later Elasticsearch.

Thanks anyway @dermidgen.

**Pull request closed without merging**
