### PR TITLE
Upgrade to support ES 5.1.2

### PR DESCRIPTION
**Pull request by vaijab**

### CODE REVIEW

**Comment by vaijab** [comment]
@pires just a gentle ping. ES 5.1.2 has some nice bugfixes. Thanks in advance! :-)

**Comment by jimmidyson** [comment]
Sorry I don't have time to try this out right now :( @pires I've given you rights to merge so feel free to do so if you have time to review/try out.

And if anyone else wants to offer to help as a maintainer, let me know please.

**Comment by jimmidyson** [comment]
ok to test

**Comment by jimmidyson** [comment]
retest this please

**Comment by pires** [comment]
@jimmidyson I can have it merged but I don't know how to trigger the release JAR build and upload. Is that automated now on PR merge? On tag?

**Pull request merged**
