### PR TITLE
Upgrade to ElasticSearch v2.4.1

### PR DESCRIPTION
**Pull request by vaijab**

### CODE REVIEW

**Comment by jimmidyson** [comment]
ok to test

**Comment by jimmidyson** [comment]
LGTM [merge]

Thanks @vaijab

**Comment by vaijab** [comment]
@jimmidyson great, thanks. Can we have a release please?

**Comment by jimmidyson** [comment]
@vaijab Of course - just about to do it.

**Comment by jimmidyson** [comment]
Syncing across to Maven central now - should be available <20 minutes from now hopefully.

**Pull request merged**
