### PR TITLE
Upgraded Elasticsearch to version 2.3.5.

### PR DESCRIPTION
**Pull request by pires**
/cc @jimmidyson

### CODE REVIEW

**Comment by davsclaus** [comment]
ok to test

**Comment by davsclaus** [comment]
[merge]

**Comment by pires** [comment]
@davsclaus just to make sure, CI bot will publish Maven artifact, right?

**Comment by davsclaus** [comment]
I dont think so. A release is triggered manually? @jimmidyson @rawlingsj

**Comment by pires** [comment]
Still no artifact 👎

**Comment by jimmidyson** [comment]
So impatient... on vacation.., see https://fabric8-ci.fusesource.com/job/elasticsearch-cloud-kubernetes-release/58/console for release build, should be synced ~20 minutes.

**Comment by pires** [comment]
Gotta cry a little bit :sob: thanks a ton, enjoy Jimmi!

**Pull request merged**
