### PR TITLE
Fix plug-in version in Dockerfile

### LINKED ISSUE #72: Invalid plugin version in docker image
Not sure if this is the correct repo for this, but the 5.2.0 image does not have the correct version of elasticsearch installed:

```
uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: Plugin [discovery-kubernetes] is incompatible with Elasticsearch [5.1.1]. Was designed for version [5.2.0]
```

```
elasticsearch@b4e01e29e890:/usr/share/elasticsearch$ elasticsearch --version
Version: 5.1.1, Build: 5395e21/2016-12-06T12:36:15.409Z, JVM: 1.8.0_111
```

### PR DESCRIPTION
**Pull request by pires**
@jimmidyson care to trigger a new image build. My bad when reviewing the PR that upgraded to 5.2.0.

Fixes #72

### CODE REVIEW

**Comment by prashantchitta** [comment]
@pires @jimmidyson Any plans to review and merge this fix?

**Comment by jimmidyson** [comment]
[merge]

**Comment by prashantchitta** [comment]
@jimmidyson Thanks for the merge. I do not see the updated image in docker hub. Can you please push the updated image to dockerhub?

**Comment by jimmidyson** [comment]
@prashantchitta Released and re-pushed fabric8/elasticsearch-k8s:5.2.0 with fixed version.

**Comment by prashantchitta** [comment]
Thanks @jimmidyson

**Pull request merged**
