### PR TITLE
Attempt to upgrade to 5.1.1

### PR DESCRIPTION
**Pull request by jcscottiii**
Addresses #56

## Note: this is just an attempt. Would like to know if someone can test this out actually.

It compiles fine. that's about it.

A lot of inspiration for this PR was drawn from 
https://github.com/elastic/elasticsearch/pull/21036/files
and 
https://github.com/elastic/elasticsearch/pull/21398/files

### CODE REVIEW

**Comment by jimmidyson** [comment]
Thanks for sending this in. I think @pires is also looking at this - might be good to collaborate on it if you can?

**Comment by pires** [comment]
I am not sure this will work but it does look a lot like what I have here. Why did you remove the `KubernetesModule` class?

**Comment by jcscottiii** [comment]
Just following what happened in https://github.com/elastic/elasticsearch/commit/60353a245a61b0a2c0121e526954b80a10e52641

They removed [`AzureDiscoveryModule.java`](https://github.com/elastic/elasticsearch/commit/60353a245a61b0a2c0121e526954b80a10e52641#diff-21a1c5e6b40b47355efc154ace8dcaefL1) and [`Ec2Module.java`](https://github.com/elastic/elasticsearch/commit/60353a245a61b0a2c0121e526954b80a10e52641#diff-66bca98a419cd6dbad4ff85dbcb99d5dL1)

**Comment by pires** [comment]
Later yesterday night, I got this to work with my changes. I will merge yours with mine and test them shortly.

**Comment by pires** [comment]
This PR as is doesn't work.

**Comment by jcscottiii** [comment]
we can close this! thanks for trying!

**Comment by pires** [comment]
```
$ kubectl logs -f es-master-726932337-z1d28
[2016-12-14T13:41:29,031][WARN ][o.e.c.l.LogConfigurator  ] ignoring unsupported logging configuration file [/elasticsearch/config/logging.yml], logging is configured via [/elasticsearch/config/log4j2.properties]
[2016-12-14T13:41:29,259][INFO ][o.e.n.Node               ] [] initializing ...
[2016-12-14T13:41:29,356][INFO ][o.e.e.NodeEnvironment    ] [kukri6j] using [1] data paths, mounts [[/data (/dev/sda9)]], net usable_space [13.4gb], net total_space [15.5gb], spins? [possibly], types [ext4]
[2016-12-14T13:41:29,357][INFO ][o.e.e.NodeEnvironment    ] [kukri6j] heap size [247.5mb], compressed ordinary object pointers [true]
[2016-12-14T13:41:29,360][INFO ][o.e.n.Node               ] node name [kukri6j] derived from node ID [kukri6j6Qq261qRUI9JN5g]; set [node.name] to override
[2016-12-14T13:41:29,364][INFO ][o.e.n.Node               ] version[5.1.1], pid[12], build[5395e21/2016-12-06T12:36:15.409Z], OS[Linux/4.8.11-coreos-r2/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_111-internal/25.111-b14]
[2016-12-14T13:41:30,437][INFO ][o.e.p.PluginsService     ] [kukri6j] loaded module [aggs-matrix-stats]
[2016-12-14T13:41:30,437][INFO ][o.e.p.PluginsService     ] [kukri6j] loaded module [ingest-common]
[2016-12-14T13:41:30,438][INFO ][o.e.p.PluginsService     ] [kukri6j] loaded module [lang-expression]
[2016-12-14T13:41:30,438][INFO ][o.e.p.PluginsService     ] [kukri6j] loaded module [lang-groovy]
[2016-12-14T13:41:30,438][INFO ][o.e.p.PluginsService     ] [kukri6j] loaded module [lang-mustache]
[2016-12-14T13:41:30,438][INFO ][o.e.p.PluginsService     ] [kukri6j] loaded module [lang-painless]
[2016-12-14T13:41:30,439][INFO ][o.e.p.PluginsService     ] [kukri6j] loaded module [percolator]
[2016-12-14T13:41:30,439][INFO ][o.e.p.PluginsService     ] [kukri6j] loaded module [reindex]
[2016-12-14T13:41:30,440][INFO ][o.e.p.PluginsService     ] [kukri6j] loaded module [transport-netty3]
[2016-12-14T13:41:30,441][INFO ][o.e.p.PluginsService     ] [kukri6j] loaded module [transport-netty4]
[2016-12-14T13:41:30,442][INFO ][o.e.p.PluginsService     ] [kukri6j] loaded plugin [discovery-kubernetes]
[2016-12-14T13:41:32,443][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.NullPointerException
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.cli.Command.main(Command.java:62) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82) ~[elasticsearch-5.1.1.jar:5.1.1]
Caused by: java.lang.NullPointerException
	at org.elasticsearch.discovery.DiscoveryModule.<init>(DiscoveryModule.java:63) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.node.Node.<init>(Node.java:410) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.node.Node.<init>(Node.java:229) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:214) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:214) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:306) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-5.1.1.jar:5.1.1]
	... 6 more
```

**Comment by jcscottiii** [comment]
hmmm. It's complains here: https://github.com/elastic/elasticsearch/blob/5.1/core/src/main/java/org/elasticsearch/discovery/DiscoveryModule.java#L63

Which would make sense since i'm returning null if the `isDiscoveryAlive` is false
https://github.com/fabric8io/elasticsearch-cloud-kubernetes/pull/57/files#diff-ca7096698946c72f3c380a746add6f40R87

I should probably return an empty map instead of null. BUT shouldn't discovery be alive anyway?

**Comment by jcscottiii** [comment]
Refer to #58

**Pull request closed without merging**
