### PR TITLE
Update elasticsearch version to 2.4.0

### PR DESCRIPTION
**Pull request by xabufr**

### CODE REVIEW

**Comment by pires** [comment]
LGTM! Can anyone merge this? @jimmidyson @davsclaus

**Comment by pires** [comment]
Oh, and please make sure the artifact is published.

**Comment by jimmidyson** [comment]
ok to test

**Comment by jimmidyson** [comment]
LGTM [merge]

**Comment by jimmidyson** [comment]
Thanks!

**Comment by pires** [comment]
Something is wrong.. ```
ERROR: Plugin [cloud-kubernetes] is incompatible with Elasticsearch [2.4.0]. Was designed for version [2.3.5]
```

**Comment by pires** [comment]
For some reason, the merge is borked https://github.com/fabric8io/elasticsearch-cloud-kubernetes/blob/master/pom.xml#L57 still points to 2.3.5.

**Comment by pires** [comment]
The merge didn't happen.

**Comment by jimmidyson** [comment]
WTF github? Commit seems to have been lost. Noone's force pushed but commit gone.

**Comment by pires** [comment]
@jimmidyson could it be something with the CI bot that hasn't pushed all commits or smth? Otherwise, let's bring @GithubHelp aboard.

**Comment by pires** [comment]
@xabufr can you reopen the PR, please?

**Comment by xabufr** [comment]
I didn't find who to reopen this one,  so I created a new one #45

**Pull request merged**
