### PR TITLE
avoid changing ownership of the data dir as it causes issues on locked down openshift clusters

### PR DESCRIPTION
**Pull request by rawlingsj**

### CODE REVIEW

**Comment by jimmidyson** [comment]
I'm a bit confused by this. It shouldn't be running as root on openshift so those lines shouldn't run?

**Comment by rawlingsj** [comment]
I think I might have something.  

There are init containers that have been added to f-m-p that chmod 777 any PVC related volumes for kubernetes resources.  There was a refactor on f-m-p and I noticed that after the openshift resources had this init container added too.  

I'm still not sure if that's intentional but I just removed the initcontainer annotation, scaled back the elasticseach DC, deleted it's PVC which removed the PV then added a new one back which means it's a clean volume.  

Scaling the DC up again and there's no chmod errors.

So perhaps this is related to this observation https://github.com/fabric8io/fabric8-maven-plugin/issues/772 and the fix is to remove the chmod 777 init container from openshift resources?

**Comment by rawlingsj** [comment]
@rhuss @jstrachan do you know anything about this issue?  I'm wondering if its intentional to be generating initcontainer annotations in fmp which chmod 777 openshift resources?  I think we originally only wanted it to apply to kubernetes resources?

**Comment by jimmidyson** [comment]
@rawlingsj The requirement to chmod PVs depends on the type of the PV. "Proper" cloud PVs with dynamic provisioning correctly set up ownership and selinux labelling. The chmod requirement is really only to do with PV implementations that don't support ownership, like host path volumes. I think it makes more sense to make this opt-in (like autotls) rather than a default enricher.

**Comment by rawlingsj** [comment]
Ok - not sure where that leaves us with this PR, is it not needed now or needs to change to optionally chmod the folder?  And I guess we still need to remove the default enricher from f-m-p for the openshift resources as I understand their PV solution does correctly handle the ownership and selinux.

**Comment by jimmidyson** [comment]
This PR shouldn't have any effect, those lines shouldn't run on OpenShift as running as arbitrary UID.

**Comment by rawlingsj** [comment]
I did a fair amount of testing and this was the only way I was able to get the fabric8 elasticsearch app to start on our openshift integration cluster. 

Im not around next week so will likely have to take another look at this the week after.

**Comment by rawlingsj** [comment]
I was on my phone earlier so my reply wasn't very clear;  this was the only test that worked when the init container runs first. If the init container doesn't run then I dont get the `'chown: changing ownership of ‘/usr/share/elasticsearch/data’: Operation not permitted'`

So if we remove the default init container enricher that chmod 777 folders from openshift resources then I think we should be good.  I'll raise a PR this weekend on f-m-p and check that all works, then release everything.  That should get the elasticsearch pod starting on openshift without this change.

**Pull request closed without merging**
