### PR TITLE
Update elasticsearch to version 5.3.1

### PR DESCRIPTION
**Pull request by jperville**
This PR compiles this plugin against version 5.3.1 of elasticsearch.

### CODE REVIEW

**Comment by jimmidyson** [comment]
ok to test

**Comment by jimmidyson** [comment]
[merge]

**Comment by jimmidyson** [comment]
Thanks @jperville!

**Comment by jimmidyson** [comment]
Released 5.3.1 - thanks for this PR.

**Comment by jperville** [comment]
@jimmidyson how long does it take for the artefacts to arrive on https://repo1.maven.org/maven2/io/fabric8/elasticsearch-cloud-kubernetes? Still no directory for "5.3.1" there yet...

**Comment by jimmidyson** [comment]
Hmm normally it takes < 20 minutes but looks like there's a problem with sonatype syncing to Maven central... Out of my control I'm afraid, but if it goes on much longer then I will raise a ticket to try to get it sorted.

**Comment by jimmidyson** [comment]
@jperville It's available now.

**Comment by jperville** [comment]
Thank you very much @jimmidyson

**Pull request merged**
