### PR TITLE
Support Elasticsearch 2.1.0

### PR DESCRIPTION
**Pull request by pires**
Upgraded Elasticsearch and Lucene dependencies.

### CODE REVIEW

**Comment by jimmidyson** [comment]
Does this break compatibility with 2.0? If so, could you update readme please with compatible versions?

**Comment by jimmidyson** [comment]
We'll do a 2.1 release for this - perhaps we'll just continually track ES version now.

**Comment by pires** [comment]
@jimmidyson I have no idea.

I know however that the version needs to match, otherwise it won't work. I agree the release should track Elasticsearch version.

```
Step 3 : RUN /elasticsearch/bin/plugin install io.fabric8/elasticsearch-cloud-kubernetes/2.0.2 --verbose
 ---> Running in b677ca205c39
-> Installing io.fabric8/elasticsearch-cloud-kubernetes/2.0.2...
Plugins directory [/elasticsearch/plugins] does not exist. Creating...
Trying https://download.elastic.co/io.fabric8/elasticsearch-cloud-kubernetes/elasticsearch-cloud-kubernetes-2.0.2.zip ...
Failed: FileNotFoundException[https://download.elastic.co/io.fabric8/elasticsearch-cloud-kubernetes/elasticsearch-cloud-kubernetes-2.0.2.zip]; nested: FileNotFoundException[https://download.elastic.co/io.fabric8/elasticsearch-cloud-kubernetes/elasticsearch-cloud-kubernetes-2.0.2.zip];
Trying https://search.maven.org/remotecontent?filepath=io/fabric8/elasticsearch-cloud-kubernetes/2.0.2/elasticsearch-cloud-kubernetes-2.0.2.zip ...
Downloading .................................................................................................................................................................................................................................................................................................................................DONE
Verifying https://search.maven.org/remotecontent?filepath=io/fabric8/elasticsearch-cloud-kubernetes/2.0.2/elasticsearch-cloud-kubernetes-2.0.2.zip checksums if available ...
Downloading .DONE
ERROR: Plugin [cloud-kubernetes] is incompatible with Elasticsearch [2.1.0]. Was designed for version [2.0.0]
```

**Comment by jimmidyson** [comment]
OK so let's just track the version & update the README in this PR please. Also change SNAPSHOT version accordingly to 2.1.0-SNAPSHOT please.

**Comment by pires** [comment]
@jimmidyson done. Please, review.

**Comment by jimmidyson** [comment]
ok to test

**Comment by jimmidyson** [comment]
add to whitelist

**Comment by jimmidyson** [comment]
LGTM - thanks @pires!

**Comment by jimmidyson** [comment]
[merge]

**Comment by pires** [comment]
Thank you @jimmidyson for giving feedback so promptly. You're an OSS god :+1:

**Comment by jimmidyson** [comment]
Aw shucks :blush: 

Thank you for updating this so quickly. You happy for a release?

**Comment by pires** [comment]
@jimmidyson I am waiting on it. Thank you once more.

**Pull request merged**
