### PR TITLE
Support ElasticSearch v5.0.0

### PR DESCRIPTION
**Pull request by aadu**
Makes the plugin compatible with Elastic Search v5. The API shouldn't change given its officially hit GA status. Note that I changed the plugin name to discovery-kubernetes to be consistent with the officially supported discovery plugins (e.g., [discovery-gce](https://www.elastic.co/guide/en/elasticsearch/plugins/5.0/discovery-gce.html).) Also, I didn't update any of the Docker settings, but have successfully tested this out on GKE.

### CODE REVIEW

**Comment by pires** [comment]
@jimmidyson LGTM however I'd maintain this in a branch specific to 5.x.

**Comment by jimmidyson** [comment]
I think I'd rather keep this as master & cut a 2.x branch - @pires wdyt?

**Comment by pires** [comment]
@jimmidyson do it! In the end it's just a new release that one can manage with their own dependency mgmt tool.

**Comment by pires** [comment]
@jimmidyson please, do it.

**Comment by jimmidyson** [comment]
ok to test

**Comment by jimmidyson** [comment]
[merge]

**Comment by jimmidyson** [comment]
Thanks @aadu! I'll get a release out soon-ish.

**Comment by pires** [comment]
@jimmidyson ping us here when the JAR gets released 👍

**Comment by jimmidyson** [comment]
Give it 20 minutes & it will be in Maven central - just syncing now.

**Pull request merged**
