### PR TITLE
Upgrade to elasticsearch 2.4.0 -  attempt two

### PR DESCRIPTION
**Pull request by xabufr**

### CODE REVIEW

**Comment by pires** [comment]
@xabufr you need to rebase from master or someone needs to force push to master. @jimmidyson sorry for pinging you, I understand if you have other priorities.

**Comment by jimmidyson** [comment]
Please rebase against master.

**Comment by xabufr** [comment]
Sorry but I don't have internet connection for now. I can only connect with the data on my mobile phone. If you got time I'll be able to do it tomorrow from my office.

**Comment by pires** [comment]
@xabufr OK I'll take care of merging this. @jimmidyson if I manually merge it into master, how can I trigger the build and artifact publishing?

**Comment by jimmidyson** [comment]
I'd like to try out the new functionality that maintainers can push to PR branches... https://github.com/blog/2247-improving-collaboration-with-forks

@pires Sadly I can't give you permission to release due to restrictions on our CI env... But I will release ASAP after this is merged.

**Comment by jimmidyson** [comment]
Sorry I really messed up the collaboration on the fork... I'll open a new PR & push there. Thanks for your work though @xabufr!

**Pull request closed without merging**
