### PR TITLE
Upgrade to 5.2.0.

### PR DESCRIPTION
**Pull request by speedplane**

### CODE REVIEW

**Comment by pires** [comment]
Please rebase.

**Comment by speedplane** [comment]
Done.

**Comment by jimmidyson** [comment]
ok to test

**Comment by jimmidyson** [comment]
Compilation error - see bottom of https://ci.fabric8.io/job/elasticsearch-cloud-kubernetes-pullreq/44/console

**Comment by speedplane** [comment]
Hmm, I tried putting this PR together as a convenience to the maintainers, but I am entirely unfamiliar with the codebase or what exactly that error is. I've been a user of this package, but do not claim to know how it works. If you could provide some insight on this build error, it would be helpful.

**Comment by pires** [comment]
It means the new release has changed the ZenDiscovery interface *again*! :man_facepalming:

**Comment by jimmidyson** [comment]
@speedplane Your PR is honestly really appreciated, thank you. It's probably a very easy fix if you're familiar with Java? If not, I'm sure someone else will pick it up soon.

@pires Shocked at how little regard they have for compatibility in the plugin API...

**Comment by pires** [comment]
@jimmidyson tell me about it.. I want to help get this going but can't say when I'll pick it up.

**Comment by speedplane** [comment]
Made the changes, builds seem to pass. Just needed to add a parameter.

**Comment by pires** [comment]
@speedplane please squash your commits and I'll have it merged.

**Comment by jimmidyson** [comment]
Nice work @speedplane!

**Comment by speedplane** [comment]
Awesome, thank you! Does it get automatically uploaded to Maven? Any idea on how long that'll take?

**Comment by jimmidyson** [comment]
No but I've released now - should be in maven central < 20 minutes.

**Pull request merged**
