### PR TITLE
Upgraded to elasticsearch 5.5.1

### PR DESCRIPTION
**Pull request by cpointner**
Upgraded to elasticsearch 5.5.1

### CODE REVIEW

**Comment by jimmidyson** [comment]
ok to test

**Comment by jimmidyson** [comment]
[merge]

**Comment by jperville** [comment]
Hello @jimmidyson , even if the PR was merged 45 min ago there is still no release yet on [maven](https://repo1.maven.org/maven2/io/fabric8/elasticsearch-cloud-kubernetes/5.5.1/). Can you trigger a release job?

**Comment by jimmidyson** [comment]
@jperville Patience! To be honest, I'd forgotten so thank you for the kick. Releasing now, sync should be <30 minutes hopefully. Please check then, any problems let me know.

**Comment by jperville** [comment]
Thank you very much @jimmidyson

**Pull request merged**
